#!/bin/bash

now=$(date)
echo "$now"

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (using sudo)"
    exit 1
fi

sudo -u "$SUDO_USER" mkdir -p res/oblivious

BASE_CASE=32
MEM_LIMIT=8388608
SWAP_LIMIT=536870912
INSTANCE_COUNTS="1 2 3 4"

CGROUP_NAME="oblivious"
CGROUP_PATH="/sys/fs/cgroup/$CGROUP_NAME"
RESULTS_FILE="res/oblivious/oblivious_results.txt"
LOG_DIR="res/oblivious"

rm -f $LOG_DIR/oblivious_*.log $RESULTS_FILE

cleanup() {
    echo "Cleaning up cgroup: $CGROUP_NAME"
    pkill -9 -f 'bin/lcs_' 2>/dev/null || true
    sleep 0.3
    rmdir "$CGROUP_PATH" 2>/dev/null || true
}
trap cleanup EXIT

echo "Setting up cgroup: $CGROUP_NAME"
mkdir -p "$CGROUP_PATH"
if [ $? -ne 0 ]; then
    echo "Failed to create cgroup directory. Exiting."
    exit 1
fi

echo $MEM_LIMIT > "$CGROUP_PATH/memory.max"
echo $SWAP_LIMIT > "$CGROUP_PATH/memory.swap.max"
echo 0 > "$CGROUP_PATH/memory.oom.group" 2>/dev/null || true

# Cgroup-wide swap traffic (pswpin+pswpout) in bytes. The instances share one
# cgroup, so we measure the whole batch from here rather than per-process.
read_cgroup_swap_bytes() {
    awk '/^pswpin /{i=$2} /^pswpout /{o=$2} END{print (i+o)*4096}' "$CGROUP_PATH/memory.stat"
}

echo "Cgroup: $CGROUP_NAME (oblivious: $(($MEM_LIMIT/1024/1024))MiB shared by N concurrent instances; cgroup-wide swap pswpin+pswpout per batch)" >> "$RESULTS_FILE"
echo "BASE_CASE: $BASE_CASE, Swap limit: $SWAP_LIMIT" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"
echo "N, Instances, Hirschberg_IO, Oblivious_IO, Ratio" >> "$RESULTS_FILE"

# Run $inst concurrent copies of $exe at size $N, all sharing the cgroup; echo the
# cgroup-wide swap (bytes) generated by the batch.
run_batch() {
    local exe="$1" N="$2" inst="$3" i
    sync; echo 3 > /proc/sys/vm/drop_caches
    local before
    before=$(read_cgroup_swap_bytes)
    for i in $(seq 1 "$inst"); do
        ( echo $BASHPID > "$CGROUP_PATH/cgroup.procs"; \
          exec stdbuf -o0 nice -n 10 ./bin/"$exe" "$N" 1 $BASE_CASE ) \
            < "rsrc/data-$N.in" > "$LOG_DIR/oblivious_${exe}_${N}_${inst}_$i.log" 2>&1 &
    done
    wait
    local after
    after=$(read_cgroup_swap_bytes)
    echo $(( after - before ))
}

for N in "${@:-131072}"; do
    for INST in $INSTANCE_COUNTS; do
        echo "Running OBLIVIOUS for N=$N with $INST instance(s)..."
        echo "  $INST x Hirschberg..."
        H=$(run_batch lcs_hirschberg "$N" "$INST")
        echo "  $INST x Oblivious..."
        O=$(run_batch lcs_oblivious "$N" "$INST")
        if [ "$O" -gt 0 ]; then
            R=$(echo "scale=6; $H / $O" | bc -l)
        else
            R=0
        fi
        echo "$N, $INST, $H, $O, $R" >> "$RESULTS_FILE"
    done
done

echo "Oblivious experiment complete. Results saved to $RESULTS_FILE."
chown -R $SUDO_USER:$SUDO_USER res/oblivious/
